### ISSUE TITLE
Solicitações de melhoria (tela atividades)

### ISSUE THREAD

**Issue by brunatotti** [ads-fatec-team3/chatbot#103]
- [x] Verificar a possibilidade de incluir calendário com marcação nos dias com atividades - @LLBueno 
- [x] Verificar a possibilidade de ao clicar no dia, visualizar a atividade - @LLBueno 
- ![image](https://user-images.githubusercontent.com/35302191/100024035-d11b4f80-2dc4-11eb-9e49-194a5638c8b1.png)
- [x] Criar array de membros dentro de agenda - @MarcioOrdonez @lebarreto  
- [x] Quando criar uma atividade deve retornar o obj da atividade - @eduns 
- [x] Botão adicionar deve ser da cor verde Gruly - @brunatotti 
- [x] As cores de prioridade devem ser: Laranja (alta); Amarelo (média); Cinza (baixa) - @brunatotti 
- [x] Diminuir o tamanho das bolinhas coloridas - @lebarreto 
- [x] Ao clicar na atividade, deve ser possível visualizar as informações - @lebarreto 
- [ ] Ao clicar na bolinha colorida, deve trocar a cor para cinza (representando que a atividade já foi finalizada) - @joaouchoas 
- [x] Alterar cor da baixa prioridade para verde - @brunatotti 
- [x] Verificar a possibilidade de incluir filtro para trazer atividades - @MarcioOrdonez 
- Alta prioridade;
- Média prioridade;
- Baixa prioridade;
- Atividades abertas;
- Atividades concluídas. 
- [x] Alterar a escrita do botão Adicionar para Criar atividade - @brunatotti 
- [x] Alterar a escrita do título de Adicionar atividade para Nova atividade @brunatotti 
- [x] Alterar a escrita do botão de Adicionar para Criar atividade - @brunatotti 
- [x] Ao clicar em Criar atividade, modal deve vir limpo.  - @lebarreto

**Comment by brunatotti** [comment]
22/11 - 30h

**Comment by lebarreto** [comment]
23/11 - 2h

**Comment by leonextlevel** [comment]
25/11 - 4h

**Comment by lebarreto** [comment]
24/11 - 2h

**Comment by eduns** [comment]
24/11 - 1h

**Comment by MarcioOrdonez** [comment]
26/11 3h
