### ISSUE TITLE
Solicitações de melhoria (tela login)

### ISSUE THREAD

**Issue by brunatotti** [ads-fatec-team3/chatbot#104]
- [x] Diminuir janela do chat para que fique confortável na tela. Ocupar uns 80% da altura da tela - @MarcioOrdonez 
- [x] Ao preencher o campo usuário e senha, ao apertar enter, fazer login - @MarcioOrdonez 
- [x] Diminuir a uns 30% da escrita Login - @brunatotti 
- [x] Diminuir a largura dos campos usuário e senha para que a distância entre a borda e o campo fique mais confortável - @brunatotti 
- [x] Trocar a escrita de username para usuário - @brunatotti 
- [x] Trocar a escrita de password para senha - @brunatotti 
- [x] Trocar a escrita do botão Login para Entrar - @brunatotti 
- [x] Aumentar horizontalmente o tamanho do botão Entrar. Deixar da mesma largura dos campos usuário e senha - @brunatotti 
- [x] Verificar a possibilidade de inserir o olho no campo senha (possibilidade de visualizar senha) - @lebarreto

**Comment by brunatotti** [comment]
21/11: 30m

**Comment by lebarreto** [comment]
23/11 - 30min
