### ISSUE TITLE
Mudar retorno na busca de uma conversa especifica

### ISSUE THREAD

**Issue by leonextlevel** [ads-fatec-team3/chatbot#128]
Endpoint: /api/conversations/{id}

Mudar retorno de messages, adicionar conteúdo e hora da mensagem.

DE:
{
  "id": 1,
  "title": "PI",
  "messages": [
    {
      "id": 1,
      "sender": {
        "id": 1,
        "name": "Diretor 1",
        "username": "diretor1"
      }
    }
  ],
  "members": []
}

PARA:
{
  "id": 1,
  "title": "PI",
  "messages": [
    {
      "id": 1,
      "sender": {
        "id": 1,
        "name": "Diretor 1",
        "username": "diretor1"
      },
      "text": "Mensagem teste",
      "timestamp": "2020-11-17T12:49:46.755+00:00"
    }
  ],
  "members": []
}

**Comment by eduns** [comment]
@LLBueno resolvido

**Comment by brunatotti** [comment]
Eduardo 17/11 - 30m
