### ISSUE TITLE
Solicitações de melhoria (tela Chat)

### ISSUE THREAD

**Issue by brunatotti** [ads-fatec-team3/chatbot#135]
- [x] Unificar abas Chat e Conversas. Ou seja, existir somente aba Chat com as funcionalidades que constam na aba Conversas. Ao clicar em uma conversa, nesta mesma aba, ser direcionado para a conversa selecionada - @raphariibeira 
- [x] Incluir seta com a funcionalidade de voltar para a lista de conversas (conforme protótipo) - @raphariibeira 
- ![image](https://user-images.githubusercontent.com/35302191/99892359-ef613e00-2c52-11eb-80db-da69ec67b3b2.png)
- [ ] Devem ser adicionadas no mínimo 2 pessoas para criar um grupo - @LLBueno
- [ ] Ao utilizar o campo pesquisar, deve ser possível iniciar uma conversa com qualquer usuário da autoescola - @LLBueno 
- ![image](https://user-images.githubusercontent.com/35302191/99892350-e4a6a900-2c52-11eb-8dc5-2403dc306223.png)
- [ ] A funcionalidade do ícone + deve ser somente para criar um grupo (selecionar pelo menos 2 pessoas) - @LLBueno 
- ![image](https://user-images.githubusercontent.com/35302191/99892413-61398780-2c53-11eb-8ce7-412455fe2684.png)
- [x] Criar as duas interfaces com os níveis de permissões. Uma com o chat boot a outra sem (Diretor e atendente sem. Aluno e instrutor com). Lembrar do requisito que o instrutor não pode falar com aluno - @GreiceCastilho 
- [x] Alterar a escrita da modal de Criar nova conversa para Criar grupo - @brunatotti 
- [x] Alterar a escrita do botão de adicionar para criar novo grupo - @brunatotti 
- [x] Informar com * verde se os campos forem obrigatórios e não permitir cadastro caso esteja vazio - @lebarreto 
- [x] Caso a conversa não tenha sido criado, dar o feedback para o usuário - @brunatotti  
- [x] A funcionalidade Pesquisar deve ser acionada ao entrar com alguma informacao - @MarcioOrdonez 
- [x] Colocar o ícone + no rodapé direito. Conforme protótipo - @rmsilva007 
- ![image](https://user-images.githubusercontent.com/35302191/99892472-f2106300-2c53-11eb-914a-d9e8ce325a49.png)
- [x] Adicionar dado da última mensagem da lista de conversa - @eduns 
- [x] Incluir mais uma coluna com o horário da última mensagem recebida ou enviada (ref whatsapp) - @eduns

**Comment by lebarreto** [comment]
24/11 - 1h30

**Comment by leonextlevel** [comment]
24/11 - 30m

**Comment by GreiceCastilho** [comment]
24/11 - 30 min

**Comment by leonextlevel** [comment]
28/11 - 6h

**Comment by MarcioOrdonez** [comment]
28/11 - 8h
27/11 - 1h
