### ISSUE TITLE
BSC Mapa estratégico

### ISSUE THREAD

**Issue by leonextlevel** [ads-fatec-team3/chatbot#20]

**Comment by rmsilva007** [comment]
Tempo estimado do projeto 8 horas
22/09 : pesquisa assunto 1 hora

**Comment by rmsilva007** [comment]
23/09 :  pesquisa layout de apresentação 1 hora

**Comment by rmsilva007** [comment]
24/09 :  adicionando os primeiros layouts 1:30 hora

**Comment by rmsilva007** [comment]
25/09: adicionando os primeiros conteúdos 1:00 hora

**Comment by rmsilva007** [comment]
28/09: finalizando o conteúdo e os ajustes de layout 3 horas
Link para acompanhamento: https://miro.com/app/board/o9J_kk8uw5Q=/

![image](https://user-images.githubusercontent.com/36994878/94431055-32c79080-016b-11eb-94af-cbda388779ab.png)

**Comment by rmsilva007** [comment]
01/10 : Como solicitado pelo professor foi adicionado data ao campo  de metas 10 minutos
BSC finalizado
![image](https://user-images.githubusercontent.com/36994878/94914099-c5747200-0480-11eb-9641-234023e607cb.png)

**Comment by rmsilva007** [comment]
**LINK PARA O BSC:** [https://miro.com/app/board/o9J_kk8uw5Q=/](url)
