### ISSUE TITLE
Atualização documento design thinking

### ISSUE THREAD

**Issue by leonextlevel** [ads-fatec-team3/chatbot#30]

**Comment by GreiceCastilho** [comment]
03/10 atualização de documento  tempo total 2:00hs
[design thinking.docx](https://github.com/ads-fatec-team3/chatbot/files/5323370/design.thinking.docx)

**Comment by GreiceCastilho** [comment]
2° Fase: 
Nesta segunda etapa conseguimos identificar que para facilitar a comunicação interna das autoescolas com sua equipe e seus alunos precisaremos desenvolver um chatbot onde será possível que seus usuários possam se comunicar por níveis de hierarquia.
Os usuários identificados como: diretor, secretária, instrutor e aluno terão níveis de acesso a determinados usuários, onde o diretor e a secretaria poderão se comunicar a todos os outros usuários, o instrutor e o aluno não poderão se comunicar entre si.
O ícone para iniciar o chat deverá ser um ícone flutuante na plataforma e-condutor de escolha do cliente anova sistemas. Quando o usuário acessar este ícone ele poderá optar em se comunicar com outras pessoas da autoescola (regras já definidas acima) ou com o bot. Através do bot o usuário terá acesso a serviço rápidos como emitir segunda via de documentos, cancelar aulas da autoescola etc.
Através do mapa mental é possível visualizar todas as etapas do projeto e definir estratégias para sua realização.
![image](https://user-images.githubusercontent.com/61737003/95021349-df5fb180-0646-11eb-90dc-e8dbc247c1a7.png)

 Figura1: Mapa mental do projeto
Definição
1° Fase:
Foi-se definido que o escopo do nosso projeto seria um chatbot inteiro entre as autoescolas com uma funcionalidade de dashboard que mostrariam as próximas datas com lembretes de acordo com a proximidade delas.
2° Fase:
Somos a empresa KAFFEE SOFTWARE, a KAFFEE nasceu para facilitar a comunicação entre empresas e pessoas através de chatbots. Nosso chatbot se chama Grully, ele é desenvolvido com a ajuda da inteligência artificial onde sempre procuramos agilizar o atendimento e auxiliar o usuário buscando usar a linguagem natural para causar a impressão de estar conversando com outra pessoa e não com um computador.
Nossa equipe é formada por profissionais comprometidos com excelência nas realizações de suas atividades e focados nas necessidades de nossos clientes.



 Idealização
1° Fase:
O projeto foi idealizado como um chatbot com níveis de usuários que possuem funcionalidades como criar conversas e exibir o dashboard com próximas datas importantes para manter os usuários informados.
2° Fase:
O projeto que será desenvolvido pela nossa equipe de especialistas está documentado no github, este projeto é opensurce e poderá ser acompanhado e consultado pelo link: https://github.com/ads-fatec-team3/chatbot
O projeto está sendo desenvolvido em JAVA 8, conta com banco SQL e frontend desenvolvido em VueJS, além da utilização de inteligência artificial.
Protótipos
1º Fase:
Foi criado um protótipo funcional para que tanto o cliente quanto os desenvolvedores possuam o mesmo entendimento sobre o que deverá ser feito. Desta maneira, nivelando as funcionalidades que serão desenvolvidas: https://xd.adobe.com/view/503a484d-6928-4e69-a0ec-ae30c1574dcb-0569/?fullscreen
2º Fase:
Para esta segunda fase desenvolvemos o protótipo do chat dos usuários por hierarquia:
https://xd.adobe.com/view/76ccd03a-4998-4da1-9f5c-ca6f4ecf4023-239f/?fullscreen






Testes
Com base no protótipo navegável tivemos a aprovação e validação do cliente, e iniciamos o desenvolvimento. 
Através do Canvas é possível planejar possíveis parceiros e fornecedores e traçar estratégias de marketing e relacionamento com os clientes. 
![image](https://user-images.githubusercontent.com/61737003/95021268-63656980-0646-11eb-8907-8565ea915024.png)

 Figura 2: Canvas da empresa. Acesso pelo link: https://miro.com/app/board/o9J_kl9_7K8=/
