### ISSUE TITLE
Canvas

### ISSUE THREAD

**Issue by leonextlevel** [ads-fatec-team3/chatbot#4]

**Comment by rmsilva007** [comment]
09/09: 1h

**Comment by rmsilva007** [comment]
10/09: 1:30 hrs

**Comment by rmsilva007** [comment]
11/09: 1 hr

**Comment by rmsilva007** [comment]
14/09: 2hrs

**Comment by rmsilva007** [comment]
15/09: 2hs 
Obs: Projeto finalizado
Link do canvas completo : https://miro.com/app/board/o9J_kl9_7K8=/

**Comment by rmsilva007** [comment]
![image](https://user-images.githubusercontent.com/36994878/94228094-82d7f600-fed2-11ea-9b9d-88651e53262c.png)
