### ISSUE TITLE
PETI - Planejamento Estratégico de TI

### ISSUE THREAD

**Issue by leonextlevel** [ads-fatec-team3/chatbot#41]

**Comment by rmsilva007** [comment]
05/10
pesquisa sobre o assunto 1horas

**Comment by rmsilva007** [comment]
06/10
inclusão de conteúdo 2 horas

**Comment by rmsilva007** [comment]
07/10
inclusão de conteúdo e finalização 2 horas
[petTiV1.pdf](https://github.com/ads-fatec-team3/chatbot/files/5347668/petTiV1.pdf)

**Comment by rmsilva007** [comment]
[petTiV1.pdf](https://github.com/ads-fatec-team3/chatbot/files/5347649/petTiV1.pdf)
