### ISSUE TITLE
Adicionar JWT backend

### ISSUE THREAD

**Issue by brunatotti** [ads-fatec-team3/chatbot#66]
Estimado 8h

**Comment by MarcioOrdonez** [comment]
29/10 3h ( estudos )

**Comment by rmsilva007** [comment]
29/10 4h (estudos e arquivos de configuração)

**Comment by rmsilva007** [comment]
03/11 2h30  modificações feitas disponíveis para verificação na branch

**Comment by eduns** [comment]
04/11 - 3h
05/11 - 2h

**Comment by eduns** [comment]
06/11 - 1h
07/11 - 2h
08/11 - 2h
09/11 - 1h
