### ISSUE TITLE
Mapeamento Objeto Relacional

### ISSUE THREAD

**Issue by leonextlevel** [ads-fatec-team3/chatbot#9]
Deve possuir, no mínimo, duas entidades mapeadas e relacionadas de forma bidirecional (OneToMany/ManyToOne ou ManyToMany/ManyToMany). Crie repositórios e, no mínimo, uma consulta com mais de um parâmetro e uma consulta que utilize dados de duas entidades (join). Utilize transação para proteger um método que realize mais de uma operação de escrita no Banco de Dados.

**Comment by rmsilva007** [comment]
19/09 : 1hr
