### ISSUE TITLE
Reunião Planejamento 02/11

### ISSUE THREAD

**Issue by leonextlevel** [ads-fatec-team3/chatbot#95]
Ementa da Reunião 02/11
Horário: Das 10 às 12:30
Duração: 2h30m
Participantes: Bruna, Eduardo, Greice, Leandro, Márcio e Robson.
Tempo gasto total: 15h

• Criou as issues da sprint 5;
• Letícia atualizar doc Matriz (caso tenha dúvida, falar aqui no grupo que a gente esclarece);
• Revisou projeto;
• Dividiu o desenvolvimento em frentes: 
     - JWT - Márcio, Eduardo e Robson;
     - IA - Leandro e Raphael;
     - Front - Bruna, João e Leandro;
     - Back - Letícia, Greice e Raphael;
     - Docs - Bruna, Greice, João, Letícia, Leandro, Raphael.

**Comment by leonextlevel** [comment]
2h30

**Comment by rmsilva007** [comment]
2h30

**Comment by brunatotti** [comment]
2h30

**Comment by GreiceCastilho** [comment]
2h

**Comment by eduns** [comment]
2h30m
