### ISSUE TITLE
Plano de gerenciamento de aquisições

### ISSUE THREAD

**Issue by brunatotti** [ads-fatec-team3/chatbot#98]
Estimado 3 horas

Depois que tiramos a duviada de o que deveria ser feito nesta atividade com o professor, verificamos que esse documento nao se aplica ao nosso projeto por nao precisar de aquisicoes

**Comment by brunatotti** [comment]
10/11/20 - 40m

**Comment by joaouchoas** [comment]
10/11/20 - 40min
