### ISSUE TITLE
Framework de help desk

### ISSUE THREAD

**Issue by brunatotti** [ads-fatec-team3/chatbot#99]
Estimado 3 horas

**Comment by rmsilva007** [comment]
04/11 1hr e 30 pesquisa

**Comment by rmsilva007** [comment]
dia 07/11
Entendimento da ferramenta e cadastro de serviços e integrantes  2:30hrs

**Comment by rmsilva007** [comment]
dia 10/11
ajustes, configurações de redes sociais e email  2:00 hrs

**Comment by rmsilva007** [comment]
11/11 
finalização e ajuste para as requisições pedidas pelo professor. 2 hrs

**Comment by rmsilva007** [comment]
12/11 
gravação do video 1:30
